=head1 NAME

Form::Sensible::FAQ - Answers to questions about how to use Form::Sensible

=head1 Validation

=over 4

=item How do I create validation that involves multiple fields (like password and confirmation fields)

Individual field based validation is handled via the individual field's C<validation> hash.  If you want
to check multiple fields together you need to do whole-form level validation.  This can be accomplished 
easily via the form's C<validation> hash as follows:

    $form->validation({
                        code => sub {
                                my ($form, $result) = @_;
                                
                                if ($form->field('password')->value() ne $form->field('password2')->value()) {
                                    $result->add_error('password2', 'Passwords do not match');
                                }
                        }
    });

=back

=head1 HTML Rendering

=over 4

=item More to come...

=back

=head2 CSS tagging

=over 4

=item More to come...

=back

=head2 HTML changes

=over 4

=item More to come...

=back


=head1 Delegates

=over 4

=item More to come, see L<Form::Sensible::Delegation> for more information.

=back

=head1 AUTHORS

Jay Kuri, C<jayk@cpan.org>

=head1 COPYRIGHT & LICENSE

Copyright (c) 2010 the aforementioned authors. All rights
reserved. This program is free software; you can redistribute
it and/or modify it under the same terms as Perl itself.

=cut
